# Generated by Django 5.2.14 on 2026-05-26 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_otpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiosafetysession',
            name='recording_file',
            field=models.FileField(blank=True, upload_to='voice_recordings/'),
        ),
    ]
