# Generated by Codex on 2026-06-16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_audiosafetysession_recording_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="PredefinedRoute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("waypoints", models.JSONField(default=list)),
                ("is_safe", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "predefined_routes",
            },
        ),
        migrations.AddField(
            model_name="trip",
            name="predefined_route",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.predefinedroute",
            ),
        ),
    ]
